import { FormEvent, useEffect, useState } from 'react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { Panel } from '../components/ui';
import api from '../lib/api';

export default function HealthPage() {
  const [metrics, setMetrics] = useState<any[]>([]);
  const [form, setForm] = useState({ steps: 8000, sleepHours: 7.5, heartRate: 62, weight: 72, hydration: 2.3 });
  const [readiness, setReadiness] = useState<any>();
  const load = () => Promise.all([api.get('/health'), api.get('/readiness')]).then(([health, ready]) => { setMetrics(health.data); setReadiness(ready.data); });
  useEffect(() => { load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); const { data } = await api.post('/health', form); setReadiness(data.readiness); load(); }
  const chart = metrics.slice().reverse().map((item) => ({ ...item, day: new Date(item.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }));
  const avg = (key: string) => {
    const values = metrics.filter((item) => item[key] !== null && item[key] !== undefined).slice(0, 14).map((item) => Number(item[key]));
    return values.length ? (values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(key === 'steps' || key === 'heartRate' ? 0 : 1) : '0';
  };
  return <div className="page"><div className="page-head"><div><p className="eyebrow">Long-term recovery trend</p><h1>Health</h1></div>{readiness && <span className="score-chip">Readiness {readiness.score}%</span>}</div><Panel title="What Counts For XP"><p className="muted">Manual health notes help the readiness model, but objective XP for steps and sleep comes from Google Health wearable syncs. That keeps the game fair.</p></Panel><div className="grid-2"><Panel title="Daily Notes"><form className="form-grid" onSubmit={submit}>{Object.entries(form).map(([key, value]) => <div key={key}><label>{key}</label><input type="number" step={key.match(/sleep|weight|hydration/) ? '.1' : '1'} value={value} onChange={(e) => setForm({ ...form, [key]: +e.target.value })} /></div>)}<button>Save health note</button></form></Panel><Panel title="14-Day Averages"><div className="stat-grid"><div className="stat"><strong>{avg('sleepHours')}h</strong><small>Sleep</small></div><div className="stat"><strong>{avg('steps')}</strong><small>Steps</small></div><div className="stat"><strong>{avg('heartRate')}</strong><small>Heart rate</small></div><div className="stat"><strong>{avg('hydration')}L</strong><small>Hydration</small></div></div>{readiness?.factors && <div className="stack" style={{ marginTop: '1rem' }}>{Object.entries(readiness.factors).map(([key, value]) => <div key={key}><p className="between muted"><span>{key}</span><b>{String(value)}%</b></p><progress value={Number(value)} max={100} /></div>)}</div>}</Panel></div><div className="grid-2"><Panel title="Recovery Trend"><div style={{ height: 280 }}><ResponsiveContainer><LineChart data={chart}><XAxis dataKey="day" stroke="#9caecb" /><Tooltip contentStyle={{ background: '#071020', border: '1px solid #3b82f6' }} /><Line dataKey="sleepHours" name="Sleep hours" stroke="#60a5fa" strokeWidth={3} /><Line dataKey="hydration" name="Hydration L" stroke="#34d399" strokeWidth={3} /></LineChart></ResponsiveContainer></div></Panel><Panel title="Load Trend"><div style={{ height: 280 }}><ResponsiveContainer><LineChart data={chart}><XAxis dataKey="day" stroke="#9caecb" /><Tooltip contentStyle={{ background: '#071020', border: '1px solid #3b82f6' }} /><Line dataKey="steps" name="Steps" stroke="#fbbf24" strokeWidth={3} /><Line dataKey="heartRate" name="Heart rate" stroke="#fb7185" strokeWidth={3} /></LineChart></ResponsiveContainer></div></Panel></div><Panel title="Recent Logs"><ul className="list">{metrics.map((item) => <li className="between" key={item.id}><span>{new Date(item.date).toLocaleDateString()}<br /><small>{item.sleepHours || 0}h sleep | {item.hydration || 0}L water | HR {item.heartRate || '-'}</small></span><strong>{item.steps || 0} steps</strong></li>)}</ul></Panel></div>;
}
